# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWho < Formula
  desc "Quickly switch Git identities (name, email, SSH key, GPG key) per repo"
  homepage "https://github.com/Kiran-B/git-who"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kiran-B/git-who/releases/download/v0.1.0/git-who_0.1.0_darwin_amd64.tar.gz"
      sha256 "6ca22dad39c1da88d203497a6b2cb8c51a8190afa3fedb45ae83a55b8813918c"

      define_method(:install) do
        bin.install "git-who"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kiran-B/git-who/releases/download/v0.1.0/git-who_0.1.0_darwin_arm64.tar.gz"
      sha256 "e5e4be3a77e4d7485c778d1feb1bfb1a6c7510293b7637ac5bf39f8d4ebc180c"

      define_method(:install) do
        bin.install "git-who"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kiran-B/git-who/releases/download/v0.1.0/git-who_0.1.0_linux_amd64.tar.gz"
      sha256 "28fdc12ae383950e41a7b986ce7696db06076cbf807b0f59a6e69df03ccb5cba"
      define_method(:install) do
        bin.install "git-who"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kiran-B/git-who/releases/download/v0.1.0/git-who_0.1.0_linux_arm64.tar.gz"
      sha256 "601e9aef4e549f42ae342c4c437c293d3fb1622dff12201cc97c8198a21ce07a"
      define_method(:install) do
        bin.install "git-who"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-who --version")
  end
end
